config/routes.rb
Rails.application.routes.draw do
  root "studies#index"
  resources :studies

end

app/models/study.rb
class Study < ActiveRecord::Base
  has_many :study_attachments, :dependent => :destroy
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  def initialize(params = {})
    file = params.delete(:file)
    files = params.delete(:files)
    super
    if files.blank?
      if !file.blank?
        self.attachments << StudyAttachment.create_from(file) if file
      end
    else
      files.each{|file|
        self.attachments << StudyAttachment.create_from(file)
      }
    end
    self
  end

  def update(params = {})
    self.study_attachments = []
    self.attachments << StudyAttachment.create_from(file) if file
    super
    self
  end

  def linkable_url
    return nil if self.url.blank?
    if self.url.match(/^http:\/\//) or self.url.match(/^https:\/\//)
      self.url
    else
      "http://#{self.url}"
    end
  end

  def attachment
    attachments.first
  end

  def attachments
    study_attachments
  end

end

app/models/study_attachment.rb
class StudyAttachment < ActiveRecord::Base
  belongs_to :study

  def self.create_from(file)
    new({:file_name=>sanitize_filename(file.original_filename),
         :content_type=>file.content_type,
         :file_contents=>file.read
        })
  end

  private

  def self.sanitize_filename(file_name)
    return File.basename(file_name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :destroy]

  # GET /studies
  # GET /studies.json
  def index
   @studies = Study.where(status: 'public')
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
  end

  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: 'Study was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def study_params
      params.fetch(:study, {})
      params.require(:study).permit(:utf8, :authenticity_token, :commit, :_method, :id, :title, :detailed_description, :url, :contact_info, :status, :brief_summary, :submitter_name, :email, :file, :image_file, :remote_image_url,:pwd)
    end

    def authenticate_user
      if !params[:pwd] and !params['study']
        render plain: "First  Only editable by authorized folks."
      end
      if params[:pwd] and params[:pwd] != ENV["PTN_PASSWORD"]
        render plain: "Second   Only editable by authorized folks."
      end
      if params['study'] and (!params['study']['pwd'] or params['study']['pwd'] != ENV["PTN_PASSWORD"])
        render plain: "Third   Only editable by authorized folks."
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/includes/_main_footer.html.erb
<div class="wrap">

  <div class='footerone'>
    <p>Sponsored by the Eunice Kennedy Shriver National Institute of Child Health and Human Development (NICHD)</p>
  <div class="contact">

  <div id='fancybox-overlay'>
    <%= image_tag("nih.png", :size => '1200x200', :title => 'Pediatric Trials') %>
  </div>


  <div class="copyright">
    <p>
      Copyright © DCRI 2017.
    </p>
  </div>
</div>

app/views/includes/_main_header.html.erb
  <div class='site-branding'>
    <div class='social'>
     <a href='https://twitter.com/PediatricTrials' style='padding-left: 8px;, width: 45px'>
        <img src='http://pediatrictrials.org/wp-content/uploads/2016/04/twitter.png' scale='0'>
      </a>
      <a href="https://www.facebook.com/PediatricTrialsNetwork" style='padding-left: 8px;, width: 45px'>
        <img src='http://pediatrictrials.org/wp-content/uploads/2016/04/facebookicon.png' scale='0'>
      </a>
      <a href="https://pediatrictrials.org/join-our-mailing-list" style='padding-left: 8px;, width: 45px'>
        <img src='http://pediatrictrials.org/wp-content/uploads/2016/04/mailicon2.png' scale='0'>
      </a>
    </div>
  </div>
  <div id='site-header'>
    <a href='http://pediatrictrials.org/' rel='home'>
      <img src='http://pediatrictrials.org/wp-content/uploads/2016/04/final_logo5.png' width='210' height='56' scale='0' style='float: right;'>
    </a>
  </div>
  <h1 class='site-title'> == $0
    <a href='http://pediatrictrials.org/' rel='home'>Pediatric Trials Network</a>
  </h1>
  <h2 class='site-description'></h2> == $0

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300,400italic' rel='stylesheet' type='text/css'>
  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/black-tie/jquery-ui.css" rel="stylesheet">
  <link href='http://pediatrictrials.org/wp-content/themes/master_parent/style.css' rel='stylesheet', type='text/css'>
  <link href='http://pediatrictrials.org/wp-content/themes/PTN_Site_rev/style.css?ver=4.7.3' rel='stylesheet', type='text/css'>
  <title>Pediatric Trials Data</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='page-template-default page page-id-556 page-parent group-blog'>
  <header id='masthead' class="site-header" role='banner'>
    <%= render 'includes/main_header' %>
  </header>

    <%= render "flashes" -%>
    <%= yield %>

  <footer>
    <%= render 'includes/main_footer' %>
  </footer>

</body>
</html>

app/views/studies/_form.html.erb
<%=  stylesheet_link_tag "studies/studies" %>
<%= form_for(@study) do |f| %>
  <% if @study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study.errors.count, "error") %> prohibited this study info from being saved:</h2>

      <ul>
      <% @study.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <p>* Title
    <%= f.text_field :title, autofocus: true, :minlength=> 4, class: "enter-info form-control", placeholder: 'study title (with acronym)', :required => true %>
    </p>
  </div>

  <div class="form-group">
    <p>* NCT ID
    <%= f.text_field :nct_id, :minlength=> 9, :maxlength=> 16, class: 'enter-info form-control', placeholder: 'ClinicalTrials.gov ID', :required => true %>
    </p>
  </div>

  <div class="form-group">
    <p>* Brief Summary
      <%= f.text_field :brief_summary, placeholder: 'brief summary of the study', class: "enter-info form-control", :required => true %>
    </p>
  </div>

  <div class="form-group">
    <p>* Submitted by
      <%= f.text_field :submitter_name, :size=>'20', :minlength=> 4, placeholder: 'name of person depositing data', class: "enter-info form-control", :required => true %>
    </p>
  </div>

  <div class="form-group">
    <p>* Email
      <%= f.text_field :email, :size=>'20', placeholder: 'email address we can use to contact you to confirm this information (this will not display publicly)', :maxlength=>"254", class: "enter-info form-control", :required => true %>
    </p>
  </div>

  <div class="form-group">
    <p>Public Contact Info
      <%= f.text_field :contact_info, placeholder: "contact info to support secondary use of this info", class: "enter-info form-control" %>
    </p>
  </div>

  <div class="form-group">
    <p>URL
    <%= f.text_field :url, :size=>'100', placeholder: 'url link to a related website', class: "enter-info form-control" %></p>
  </div>

  <div class="form-group">
    <p>Details
      <%= f.text_area :detailed_description, cols: '40', rows: '10', placeholder: "all the details you consider worth sharing", class: 'enter-info form-control' %>
    </p>
  </div>

  <p class='enter-label form-group'>Attachment:
    <%= f.file_field :file, class: 'enter-info form-control' %>
  </p>

  <p class='enter-label form-group'>Image:
    <%= f.file_field :image_file, class: 'enter-info form-control' %>
  </p>

  <br>
  <p>By pressing this button, you agree to share this information with the research community; your information will be published to the PTN Public Repository.</p>
  <div class="button actions">
    <p><%= f.submit %></p>
  </div>

<% end %>

app/views/studies/edit.html.erb
<div class="wrap">
  <h1>Study Information</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @study %> |
  <%= link_to 'Back', studies_path %>

</div>

app/views/studies/index.html.erb
<div id='primary' class='content-area'> == $0
  <main id='main' class='site-main' role='main'>
  <div class='centercol'>
    <header class='entry-header'>
       <h1>Data Sharing</h1>
    </header>
    <div class='entry-content'>
      <p>To help expand the knowledge base for pediatric medicine, the PTN is pleased to share trial documents and data from its completed and published studies with interested investigators.  Our gaol is to be as transparent as possible with our research for the benefit of children.</p>
      <ul>
         <li>Data sharing policy</li>
         <li>Data sharing request form</li>
         <li>More information on data sharing from the Data Across Sectors for Health (DASH) collaboration</li>
      </ul>
    </div>

    <h3>Currently available studies:</h3>
    <section class="studyInfo">

      <table id='studyInfoTable' class='table dataTable data-table table-striped table-condensed table-hover'>

       <tbody>
        <% @studies.each do |study| %>
          <tr>
            <!-- <td>
              <a target='_blank' href='<%= study.id %>'>
                <% if study.image? %>
                  <%= image_tag study.image_url(:thumb) %>
                <% end %>
              </a>
            </td>  -->
            <td>
              <a href='/studies/<%= study.id %>' class='study'>
                <h4><%= study.title %></h4>
                <p><%= study.brief_summary %></p>
               <% if !study.submitter_name.blank? %>
                  <p><i>Provided by <%= study.submitter_name %></i></p>
                  <p><%= study.contact_info %></i></p>
                <% end %>
              </a>
              <% if !study.url.blank? %>
                <p><a href="<%= study.linkable_url %>" target="_blank" ><%= study.url %></a></p>
              <% end %>
            </td>
          </tr>
        <% end %>
       </tbody>
     </table>
    </section>
  </div>
  </main>
</div>

app/views/studies/new.html.erb
<div class="wrap">
  <h1>deposit your data sets...</h1>
  <p> </p>
  <%= render 'form' %>
  <p><%= link_to 'changed my mind - back out', studies_path %></p>
</div>

app/views/studies/show.html.erb
<%=  stylesheet_link_tag 'studies/studies' %>
<p id="notice"><%= notice %></p>

<div class="wrap">

  <% if @study.status != 'public' %>
    <section class='studyInfo'>
      <div class='well'>
        <h5>The information you provide will appear in the PTN Repository once it has been reviewed by DCRI faculty. You will be contacted via email to verify the content and confirm the information.</h5>
      </div>
    </section>
  <% end %>

  <br>

  <section class='studyInfo'>
    <p>
    <div class='studyInfo'>
      <% if @study.image %>
        <p class='headingImage' align="middle">
          <a href='<%= @study.image %>' target='_blank' >
            <%= image_tag @study.image_url(:medium) %>
          </a>
        </p>
      <% end %>
      <p class='headingText'><%= @study.title %></p>
    </div>
    </p>

    <% if !@study.brief_summary.blank? %>
      <p><span class='studyInfoLabel'>Summary:</span> <%= @study.brief_summary %></p>
    <% end %>

    <% if !@study.detailed_description.blank? %>
      <p><span class='studyInfoLabel'>Details:</span> <%= @study.detailed_description %></p>
    <% end %>

    <p><%= @study.submitter_name %></p>
    <p><%= @study.contact_info %></p>

    <% if @study.url %>
      <p><a href="<%= @study.linkable_url %>" target="_blank" ><%= @study.url %></a></p>
    <% end %>

    <% if !@study.attachment.nil? %>
      <p><span class='studyInfoLabel'>Dataset:</span>&nbsp;&nbsp;
        <a href='/use_case_attachments/<%= @study.attachment.id %>'>
          <%= @study.attachment.file_name %>
        </a>
      </p>
    <% end %>

    <p><span class='studyInfoLabel'>Submitted:</span> <%= @study.created_at.strftime('%Y-%m-%d %T') %></p>
  </section>

  <div style="margin:30px;">
    <p><%= link_to 'Return to List of PTN Studies', studies_path %></p>
  </div>

</div>